//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATTANAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaInfo
    {
        public AreaInfo()
        {
            this.MAgencies = new HashSet<MAgency>();
        }
    
        public string Id { get; set; }
        public string AreaName { get; set; }
        public string Describes { get; set; }
    
        public virtual ICollection<MAgency> MAgencies { get; set; }
    }
}
