//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATTANAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarInfo
    {
        public CalendarInfo()
        {
            this.MStaffs = new HashSet<MStaff>();
        }
    
        public string Id { get; set; }
        public Nullable<int> CMonth { get; set; }
        public Nullable<int> CYear { get; set; }
        public Nullable<int> CWeek { get; set; }
        public Nullable<int> FDay { get; set; }
        public Nullable<int> TDay { get; set; }
        public Nullable<int> IsClock { get; set; }
        public Nullable<int> GroupNumber { get; set; }
    
        public virtual ICollection<MStaff> MStaffs { get; set; }
    }
}
