//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATTANAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNumber
    {
        public string Id { get; set; }
        public Nullable<int> Number { get; set; }
        public string Code { get; set; }
        public Nullable<int> CYear { get; set; }
    }
}
