//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATTANAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public string OrderId { get; set; }
        public string ProductId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> QuantityBuy { get; set; }
        public Nullable<int> QuantityReal { get; set; }
    
        public virtual MOrder MOrder { get; set; }
        public virtual MProduct MProduct { get; set; }
    }
}
