//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATTANAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public ProductType()
        {
            this.MProducts = new HashSet<MProduct>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MProduct> MProducts { get; set; }
    }
}
