//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattanaSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarWork
    {
        public string Id { get; set; }
        public Nullable<int> CDay { get; set; }
        public Nullable<int> InPlan { get; set; }
        public string TypeId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.TimeSpan> CInTime { get; set; }
        public Nullable<System.TimeSpan> COutTime { get; set; }
        public string DayInWeek { get; set; }
        public Nullable<int> Perform { get; set; }
        public string CDate { get; set; }
        public string AgencyId { get; set; }
        public string MUser { get; set; }
        public string StaffCode { get; set; }
        public Nullable<int> CYear { get; set; }
        public Nullable<int> CMonth { get; set; }
        public string CalendarId { get; set; }
        public Nullable<double> Targets { get; set; }
    
        public virtual MAgency MAgency { get; set; }
        public virtual CalendarInfo CalendarInfo { get; set; }
    }
}
