//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattanaSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarWork
    {
        public string Id { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Perform { get; set; }
        public string CDate { get; set; }
        public Nullable<int> CDay { get; set; }
        public Nullable<int> CMonth { get; set; }
        public Nullable<int> CYear { get; set; }
        public string AgencyId { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> CountWork { get; set; }
        public Nullable<System.DateTime> FistTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string DayOfWeek { get; set; }
    
        public virtual MAgency MAgency { get; set; }
        public virtual MStaff MStaff { get; set; }
    }
}
