//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattanaSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarInfo
    {
        public CalendarInfo()
        {
            this.CalendarWorks = new HashSet<CalendarWork>();
            this.MStaffs = new HashSet<MStaff>();
        }
    
        public string Id { get; set; }
        public Nullable<int> IsLock { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> WeekOfYear { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserCreate { get; set; }
        public Nullable<int> CYear { get; set; }
    
        public virtual ICollection<CalendarWork> CalendarWorks { get; set; }
        public virtual ICollection<MStaff> MStaffs { get; set; }
    }
}
