//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattanaSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MDBEntities : DbContext
    {
        public MDBEntities()
            : base("name=MDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaInfo> AreaInfoes { get; set; }
        public virtual DbSet<CalendarType> CalendarTypes { get; set; }
        public virtual DbSet<CalendarWork> CalendarWorks { get; set; }
        public virtual DbSet<MAgency> MAgencies { get; set; }
        public virtual DbSet<MProduct> MProducts { get; set; }
        public virtual DbSet<MStaff> MStaffs { get; set; }
        public virtual DbSet<CalendarInfo> CalendarInfoes { get; set; }
        public virtual DbSet<MOrder> MOrders { get; set; }
        public virtual DbSet<OrderNumber> OrderNumbers { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<ProductOrder> ProductOrders { get; set; }
    
        public virtual ObjectResult<get_detail_calendar_by_calendarid_Result> get_detail_calendar_by_calendarid(string calendarId)
        {
            var calendarIdParameter = calendarId != null ?
                new ObjectParameter("calendarId", calendarId) :
                new ObjectParameter("calendarId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_detail_calendar_by_calendarid_Result>("get_detail_calendar_by_calendarid", calendarIdParameter);
        }
    
        public virtual ObjectResult<show_user_role_Result> show_user_role()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<show_user_role_Result>("show_user_role");
        }
    
        public virtual int delete_calendar(string calendarId)
        {
            var calendarIdParameter = calendarId != null ?
                new ObjectParameter("calendarId", calendarId) :
                new ObjectParameter("calendarId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_calendar", calendarIdParameter);
        }
    }
}
