//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MattanaSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public OrderStatu()
        {
            this.MOrders = new HashSet<MOrder>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string PreStt { get; set; }
        public Nullable<int> PermitUser { get; set; }
    
        public virtual ICollection<MOrder> MOrders { get; set; }
    }
}
